#!/usr/bin/env python3
"""
scripts/audit_one_story.py — Full-pipeline cost audit for one story.

Runs a complete story generation end-to-end with cost tracking enabled,
then prints a detailed cost breakdown by stage, estimates stories-per-$300,
and ranks the top 3 cost drivers with optimization suggestions.

TTS and images are generated by default. Use flags to skip them:
  --no-tts     skip audio synthesis (text passes only)
  --no-images  skip image generation

Usage:
    python scripts/audit_one_story.py
    python scripts/audit_one_story.py --no-images
    python scripts/audit_one_story.py --no-tts --no-images  # cheapest audit

Output files:
    logs/cost_audit.jsonl        all API call records (appended)
    drafts/<timestamp>/          the generated story (not promoted)

IMPORTANT: Run scripts/check_routing.py first to confirm Vertex AI routing.
"""

import argparse
import json
import sys
import time
from datetime import datetime
from pathlib import Path

# ── Project root on path ────────────────────────────────────────────────────────
ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))
sys.stdout.reconfigure(encoding="utf-8")

from dotenv import load_dotenv
load_dotenv(ROOT / ".env")

from lib.config       import load_categories, load_index, DRAFTS_DIR, LOGS_DIR
from lib.cost_tracker import (
    set_stage, get_stage, print_daily_summary, get_session_total,
)

LOGS_DIR.mkdir(exist_ok=True)
DRAFTS_DIR.mkdir(exist_ok=True)

INR_PER_USD  = 83.0
GCP_BUDGET   = 300.0   # total free credit in USD


# ── Cost snapshot helper ────────────────────────────────────────────────────────

def _snap() -> float:
    return get_session_total()


# ── Stage-cost breakdown from session JSONL ─────────────────────────────────────

def _read_session_records(since_ts: str) -> list[dict]:
    """Return all JSONL records written after since_ts in this session."""
    log = LOGS_DIR / "cost_audit.jsonl"
    if not log.exists():
        return []
    out = []
    with open(log, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                r = json.loads(line)
                if r.get("timestamp", "") >= since_ts:
                    out.append(r)
            except json.JSONDecodeError:
                pass
    return out


def _stage_breakdown(records: list[dict]) -> dict[str, dict]:
    by_stage: dict[str, dict] = {}
    for r in records:
        s = r.get("stage", "unknown")
        e = by_stage.setdefault(s, {"cost": 0.0, "calls": 0,
                                     "input": 0, "output": 0, "chars": 0,
                                     "billing_unit": r.get("billing_unit", "tokens")})
        e["cost"]  += r.get("cost_usd", 0.0)
        e["calls"] += 1
        unit = r.get("billing_unit", "tokens")
        if unit == "tokens":
            e["input"]  += r.get("input_count",  0) or 0
            e["output"] += r.get("output_count", 0) or 0
        elif unit == "characters":
            e["chars"]  += r.get("input_count",  0) or 0
    return by_stage


# ── Optimization suggestions ────────────────────────────────────────────────────

_SUGGESTIONS: dict[str, str] = {
    "validation": (
        "Consider lowering _VALIDATION_THRESHOLD from 8.0 to 7.5 — "
        "each retry is a full narration + validation pair (~2× the normal cost). "
        "Or cache validation and skip retry if score >= 7.0."
    ),
    "narration": (
        "Narration is the largest single text call. "
        "Batching all scenes into one prompt (already done) is optimal. "
        "If trimming cost, reduce max_scene_count from 8 to 6 — saves ~25% of narration tokens."
    ),
    "narration_visuals": (
        "Pass 2.5 (visual extraction) runs even when scenes are already grounded. "
        "Could be merged into Pass 2 prompt to save one round-trip."
    ),
    "outline": (
        "Outline (Pass 1) is concise. "
        "If cost is significant, reduce scenes_requested from 8 to 6 to shrink the outline."
    ),
    "translation": (
        "Translation (Pass 4) is a single batched call — already optimal. "
        "If not serving English-language users, this pass can be skipped entirely."
    ),
    "tts_generation": (
        "TTS is billed per character. "
        "If using gemini-2.5-flash-preview-tts, consider switching to Chirp3-HD for "
        "scenes with less expressive requirements — pricing may differ. "
        "Also: skip TTS regeneration if audio already exists (add cache check)."
    ),
    "image_generation": (
        "Image generation is the most time-consuming but may be billed separately. "
        "Consider generating images only for promoted stories, not all drafts."
    ),
    "unknown": (
        "Some calls have no stage tag — add set_stage() calls to the relevant module "
        "for accurate breakdown."
    ),
}

def _get_suggestion(stage: str) -> str:
    for key, suggestion in _SUGGESTIONS.items():
        if key in stage.lower():
            return suggestion
    return "No specific optimization suggestion for this stage."


# ── Main audit flow ─────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Cost audit — one full story")
    parser.add_argument("--no-tts",    action="store_true", help="Skip TTS generation")
    parser.add_argument("--no-images", action="store_true", help="Skip image generation")
    parser.add_argument("--category",    metavar="CAT",   help="Force category key")
    parser.add_argument("--subcategory", metavar="SUB",   help="Force subcategory key")
    parser.add_argument("--topic",       metavar="TOPIC", help="Force topic")
    args = parser.parse_args()

    SEP  = "=" * 66
    sep2 = "-" * 66

    print(f"\n{SEP}")
    print("  Telugu Katalu — Story Cost Audit")
    print(f"  {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(SEP)

    # ── Confirm routing before spending anything ────────────────────────────────
    from lib.config import GCP_PROJECT_ID, GCP_LOCATION
    if not GCP_PROJECT_ID:
        print("\n[ERROR] GCP_PROJECT_ID not set — run scripts/check_routing.py first.")
        sys.exit(1)
    print(f"\n  Routing  : Vertex AI | project={GCP_PROJECT_ID} | location={GCP_LOCATION}")
    print(f"  TTS      : {'SKIPPED' if args.no_tts else 'enabled'}")
    print(f"  Images   : {'SKIPPED' if args.no_images else 'enabled'}")

    # ── Slot selection ──────────────────────────────────────────────────────────
    categories = load_categories()
    stories    = load_index().get("stories", [])

    if args.category and args.subcategory and args.topic:
        cat_key, sub_key, topic = args.category, args.subcategory, args.topic
    else:
        from lib.balancer import pick_next_slot
        cat_key, sub_key, topic = pick_next_slot(categories, stories)

    cat = categories[cat_key]
    sub = cat["subcategories"][sub_key]
    print(f"\n  Category : {cat['telugu_name']} / {sub['telugu_name']}")
    print(f"  Topic    : {topic}")
    print(f"\n{sep2}")
    print("  Starting pipeline — cost lines will appear below each API call")
    print(sep2)

    # ── Record start position in JSONL ──────────────────────────────────────────
    audit_start_ts = datetime.utcnow().isoformat() + "Z"
    cost_before    = _snap()
    t0_wall        = time.time()

    # ── Pass 1-4: Story text generation ─────────────────────────────────────────
    from lib.story_gen import generate_story
    story = generate_story(cat_key, sub_key, topic, categories, stories)

    text_cost = _snap() - cost_before

    # ── TTS ──────────────────────────────────────────────────────────────────────
    tts_cost = 0.0
    if not args.no_tts:
        tts_before = _snap()
        timestamp  = datetime.now().strftime("%Y%m%d_%H%M%S")
        draft_dir  = DRAFTS_DIR / timestamp
        audio_dir  = draft_dir / "audio"
        audio_dir.mkdir(parents=True, exist_ok=True)

        set_stage("tts_generation")
        from lib.tts import synthesize_story
        synthesize_story(story["scenes"], story.get("voice", ""), audio_dir)
        tts_cost = _snap() - cost_before - text_cost
    else:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        draft_dir = DRAFTS_DIR / timestamp
        draft_dir.mkdir(parents=True, exist_ok=True)

    # ── Images ───────────────────────────────────────────────────────────────────
    img_cost = 0.0
    if not args.no_images:
        from lib.image_gen import generate_images_for_story
        image_dir = draft_dir / "images"
        image_dir.mkdir(parents=True, exist_ok=True)
        img_before = _snap()
        set_stage("image_generation")
        story_with_meta = dict(story, id=timestamp, category=cat_key, subcategory=sub_key)
        generate_images_for_story(story_with_meta, draft_dir, LOGS_DIR)
        img_cost = _snap() - img_before

    # ── Save story.json ──────────────────────────────────────────────────────────
    story.update({
        "id": timestamp, "date": datetime.now().strftime("%Y-%m-%d"),
        "category": cat_key, "subcategory": sub_key, "topic": topic,
        "defaultSpeed": 1.1,
    })
    (draft_dir / "story.json").write_text(
        json.dumps(story, ensure_ascii=False, indent=2), encoding="utf-8"
    )

    wall_time   = time.time() - t0_wall
    total_cost  = _snap() - cost_before
    records     = _read_session_records(audit_start_ts)
    by_stage    = _stage_breakdown(records)

    # ── Print audit report ───────────────────────────────────────────────────────
    print(f"\n\n{SEP}")
    print("  COST AUDIT REPORT")
    print(SEP)

    print(f"\n  Story   : {story.get('title', '(no title)')}")
    print(f"  Scenes  : {len(story.get('scenes', []))}")
    print(f"  Score   : {story.get('quality_score', 0.0):.2f}/10")
    print(f"  Voice   : {story.get('voice', '(none)')}")
    print(f"  Wall    : {wall_time:.0f}s")

    # ── Cost breakdown by stage ──────────────────────────────────────────────────
    print(f"\n{sep2}")
    print("  Cost Breakdown by Stage")
    print(sep2)
    print(f"  {'Stage':<28} {'Cost (USD)':>12}  {'Calls':>5}  Usage")

    total_verified = 0.0
    for stage, d in sorted(by_stage.items(), key=lambda x: -x[1]["cost"]):
        unit = d["billing_unit"]
        if unit == "tokens":
            usage = f"in={d['input']:,} out={d['output']:,} tok"
        else:
            usage = f"{d['chars']:,} chars"
        print(f"  {stage:<28} ${d['cost']:>10.5f}  {d['calls']:>5}  {usage}")
        total_verified += d["cost"]

    print(f"\n  {'TOTAL':<28} ${total_verified:>10.5f}")
    print(f"  {'(INR approx)':<28}  Rs {total_verified * INR_PER_USD:>8,.2f}")

    # ── Per-component summary ────────────────────────────────────────────────────
    print(f"\n{sep2}")
    print("  Component Summary")
    print(sep2)
    print(f"  Text generation (Passes 1-4)  : ${text_cost:.5f}")
    if not args.no_tts:
        print(f"  TTS audio                      : ${tts_cost:.5f}")
    if not args.no_images:
        print(f"  Image generation               : ${img_cost:.5f}")
        print(f"  (note: Imagen billed separately in GCP; cost above = $0 if no token response)")
    print(f"  TOTAL this story               : ${total_cost:.5f}  (Rs {total_cost * INR_PER_USD:.2f})")

    # ── $300 runway estimate ─────────────────────────────────────────────────────
    print(f"\n{sep2}")
    print("  $300 Free Credit Runway Estimate")
    print(sep2)
    if total_cost > 0:
        stories_per_300 = GCP_BUDGET / total_cost
        print(f"  Cost per story     : ${total_cost:.5f}  (Rs {total_cost * INR_PER_USD:.2f})")
        print(f"  Stories per $300   : {stories_per_300:,.0f} stories")
        print(f"  [$300 at this rate would last {stories_per_300 / 30:.0f} months at 30 stories/month]")
    else:
        print("  No billable API calls recorded — check routing and try again.")

    # ── Top 3 most expensive stages ──────────────────────────────────────────────
    print(f"\n{sep2}")
    print("  Top 3 Cost Drivers and Optimization Suggestions")
    print(sep2)
    top3 = sorted(by_stage.items(), key=lambda x: -x[1]["cost"])[:3]
    for rank, (stage, d) in enumerate(top3, 1):
        pct = (d["cost"] / total_cost * 100) if total_cost > 0 else 0
        print(f"\n  #{rank}  {stage}  —  ${d['cost']:.5f}  ({pct:.1f}% of total)")
        suggestion = _get_suggestion(stage)
        # Word-wrap at 70 chars
        words = suggestion.split()
        line, lines = [], []
        for w in words:
            if len(" ".join(line + [w])) > 68:
                lines.append(" ".join(line))
                line = [w]
            else:
                line.append(w)
        if line:
            lines.append(" ".join(line))
        for l in lines:
            print(f"       {l}")

    # ── Grounding summary (if KB was run) ────────────────────────────────────────
    grounding = [r for r in records if r.get("billing_unit") == "grounded_queries"]
    if grounding:
        total_queries = sum(r.get("input_count", 0) for r in grounding)
        est_vertex    = sum(r.get("estimated_vertex_cost_usd", 0.0) for r in grounding)
        print(f"\n{sep2}")
        print("  Google Search Grounding (AI Studio free tier)")
        print(sep2)
        print(f"  Queries run    : {total_queries}")
        print(f"  Billed to GCP  : $0.00  (free on AI Studio)")
        print(f"  Vertex equiv   : ${est_vertex:.3f}  (would cost this if moved to Vertex)")

    print(f"\n{SEP}")
    print(f"  Draft saved: drafts/{timestamp}/")
    print(f"  Full JSONL:  logs/cost_audit.jsonl")
    print(SEP + "\n")


if __name__ == "__main__":
    main()
